chore: add relevant workflows
evmos/go-ethereum pull request #1
Opened 2023-01-09 10:28 UTC by Vvaradinov

This PR adds the relevant CI workflows from Evmos/Ethermint

2023-01-09 13:13 UTC, Vvaradinov commented
@fedekunze can you check the settings of this repo and enable the dependency graph? The CI run is giving me this error `Please ensure that Dependency graph is enabled along with GitHub Advanced Security on private repositories`

2023-01-09 17:27 UTC, fedekunze reviewed
Needs changes as the default branch is `master`. We also need to set up the `codeql.yaml` since it's not enabled by default

2023-01-09 17:27 UTC, fedekunze commented on .github/workflows/build.yml
> +      - main
@Vvaradinov needs to be changed to `master`
```suggestion
      - master
```

2023-01-10 16:25 UTC, fedekunze requested changes

2023-01-10 16:25 UTC, fedekunze commented on .github/workflows/lint.yml
> +      - main
```suggestion
      - master
```

2023-01-10 16:25 UTC, fedekunze commented on .github/workflows/markdown-links.yml
> +      - main
```suggestion
      - master
```

2023-01-10 16:25 UTC, fedekunze commented on .github/workflows/security.yml
> +      - main
```suggestion
      - master
```

2023-01-10 16:25 UTC, fedekunze commented on .github/workflows/super-linter.yml
> +    branches: ["main"]
```suggestion
    branches: ["master"]
  pull_request:
    branches: ["master"]
```

2023-01-10 16:25 UTC, fedekunze commented on .github/workflows/super-linter.yml
> +          DEFAULT_BRANCH: "main"
```suggestion
          DEFAULT_BRANCH: "master"
```

2023-01-10 16:25 UTC, fedekunze commented on .github/workflows/test.yml
> +      - main
```suggestion
      - master
```

2023-01-10 16:25 UTC, fedekunze commented on .github/workflows/test.yml
> +    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"
```suggestion
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"
```

2023-01-10 16:26 UTC, fedekunze approved these changes

2023-01-10 16:49 UTC, merged

2023-01-31 16:41 UTC, fedekunze commented
@mergifyio backport release/1.10